### ISSUE TITLE
本项目的底层支撑是什么

### ISSUE THREAD

**Issue by ShangwenWang** [InfiniTensor/InfiniLM#6]
尊敬的作者，

你们好！感谢你们精彩的工作，非常的有意义

我想了解一下，本项目用Rust语言编写，那在运行时是如何提供底层支撑的呢，是通过修改cuda使其支撑rust语言吗？

**Comment by YdrMaster** [comment]
你好，不用客气。本项目基于 Cuda Driver API、NVRTC 和 Cublas 实现 Nvidia GPU 计算卸载。

- 驱动的 Rust FFI 部分，参见[这个项目](https://github.com/YdrMaster/cuda-driver)；
- cuda kernel 部分，你可以在[这个目录](https://github.com/InfiniTensor/InfiniLM/tree/main/devices/nvidia/src)找到一些 .cu 文件；

**Comment by YdrMaster** [comment]
@ShangwenWang 如果解答了你的疑问，可以关闭 issue
